# Builds and publishes any packages

name: Publish

# On updates to release branches
on:
  push:
    branches:
      - main
      - master
      - next
      - next-major
      - beta
      - alpha

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      packages: write

    steps:
      - name: ✨ Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 🛂 Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: 🏗 Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: adopt

# Do release things
